### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by Stynson** [beardsvibe/leengine#1]
Bgfx used as a 3rd party, and it has a BSD license
Since this project can't be licensed with MIT, should be BSD too

**Comment by jimon** [comment]
bgfx here is still under BSD license, see https://github.com/beardsvibe/leengine/blob/master/3rdparty/bgfx/include/bgfx.h#L1-L6
Since this project uses bgfx instead of modifying it, so what is a reason why it should be BSD as well?
